version: '3.8'

services:
  app:
    build:
      context: .
    container_name: API
    command: >
      bash -c "python manage.py makemigrations api && python manage.py migrate && uvicorn backend.asgi:application --host 0.0.0.0 --port 8000 --workers 4"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/backend_db
    networks:
      - backend

  redis:
    image: docker.io/redis:6
    container_name: redis

    volumes:
      - redis_data:/data

    networks:
      - backend

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432' # Exposing PostgreSQL on port 5432
    networks:
      - backend

volumes:
  postgres_data:
    driver: local
  redis_data: {}

networks:
  backend:
    driver: bridge
